travis:
  secure:
    BINSTAR_TOKEN: jgWq95l4cjLqRCJnKMSX6FvnHbpPAo0PGzdJtwlbMEIER4TJwyhnmd1bhECtY20RSXPxPCfiMBwVkODJGVYBOmtiY7SQwDVLFU48VtM0E6jZZoC2P7NIxrQRw1veGZ8ke634Ajhq+0hHbG7RnSLFmheM+x/lueuUNDeCcHJ/aT0Hrpf9Gt+iw5slzSUhmcuTHUdL7DV/ljeKvOX38UZzuIZTjcQRaipKamZb5mZ8z/FdQ7JwbjZ7I1+zFNqtL0O2M7Bu76TEmoXkKA6sfk1nLKa0/a433OloW41B8yGD7OE/aDYsYbx620qIrD5G05Y3ecGg8MKVWWRC2JSwlCqovj1jgX17C3oEXCkKLYD1/qToADR0So7dcyPS6ARfENXi89p3tIy1Mgj0IwSDxlxFqwXtISY8s6zsnp0cOzrg770m5nP15aWLyMTgJx8xZbESvsRnJTkWcShU9ll0GVa7xux47+e3PxbBhWWkbYkpyiSb5xqjRuMDQqHclzU8DS9MuQ+pqsiHpqB1X1/RxeZM9UzxRRTBuApJOSKTRF406zwkpNh6BSxqWNM7NzCjISuG73OHU7afSg/KQbnl12uF0Dv22nNjrHBHxQUukVkvYObIcrBxMt8WW4oodtAognDgtdYczC4Y70WeR+mx7xJ7LwKVQ6RpICZcz3UGBDqC4jM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
